Check if issue is mentioned in changelog. (#457)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,9 +11,56 @@ on:
 
 jobs:
 
-  build:
+  changelog-check:
+    runs-on: ubuntu-20.04
+    if: ${{ github.event_name == 'pull_request' }}
 
+    env:
+      PR_BODY: ${{ github.event.pull_request.body }}
+      CHANGELOG_ISSUE: ":issue:`${{ github.event.pull_request.number }}`"
+
+    steps:
+    - uses: actions/checkout@v2
+    - name: Run check
+      run: |
+        if [ ! -z "${{ github.event.pull_request.number }}" ]; then
+          if grep -qE '^\[no changelog\]$' <<<"$PR_BODY"; then
+            echo 'Marker "[no changelog]" found in PR body'
+            if [ "$(grep -F "$CHANGELOG_ISSUE" CHANGELOG.rst)" != "" ]; then
+              echo "ERROR: $CHANGELOG_ISSUE found in CHANGELOG.rst."
+              exit 1
+            else
+              echo "OK: $CHANGELOG_ISSUE not found in CHANGELOG.rst"
+            fi
+          else
+            echo 'Marker "[no changelog]" not found in PR body'
+            if [ "$(grep -F "$CHANGELOG_ISSUE" CHANGELOG.rst)" == "" ]; then
+              echo "ERROR: $CHANGELOG_ISSUE not found in CHANGELOG.rst."
+              exit 1
+            else
+              echo "OK: $CHANGELOG_ISSUE found in CHANGELOG.rst"
+            fi
+          fi
+        fi
+        exit 0
+
+  release-check:
+    runs-on: ubuntu-20.04
+
+    steps:
+    - uses: actions/checkout@v2
+    - name: Setup environment
+      run: |
+        echo "GITHUB_PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
+      shell: bash
+    - name: Run release_checklist
+      run: |
+        admin/release_checklist --no-verify-tags --no-verify-docs-next-version 4.2
+ 
+  build:
     runs-on: ${{ matrix.os }}
+    needs: [changelog-check, release-check]
+
     strategy:
       fail-fast: false
       matrix:
@@ -76,9 +123,6 @@ jobs:
     - name: Install dependencies
       run: |
         make setup-dev
-    - name: Run release_checklist
-      run: |
-        admin/release_checklist --no-verify-tags --no-verify-docs-next-version 4.2
     - name: Lint with flake8
       run: |
         make lint
@@ -100,9 +144,9 @@ jobs:
         make doc
   
   run-docker:
-
     runs-on: ubuntu-18.04
-  
+    needs: [changelog-check, release-check]
+
     strategy:
       fail-fast: false
       matrix:
